# Generated by Django 4.2.13 on 2024-05-24 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_desert_reservation_desert_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='is_approved',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
