# Generated by Django 4.2.13 on 2024-05-24 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_notification_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='users',
        ),
    ]
