# Generated by Django 4.2.13 on 2024-05-24 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_notification_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='notification',
            name='User_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
