# Generated by Django 4.2.13 on 2024-05-24 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_notification_restaurant_notification_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='is_reserved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='is_approved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
