# Generated by Django 4.2.13 on 2024-05-30 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_reservation_order_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='order_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
